name: Java CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # 1. SETUP
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 2. BUILD
      - name: Build (compilar)
        run: javac *.java

      # 3. TEST
      - name: Rodar testes
        run: java AppTest

      # 4. RELEASE (simples)
      - name: Gerar artefato .jar
        run: |
          jar cfe app.jar App *.class

      - name: Upload artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: app.jar
